### ISSUE TITLE
Create Mesh Component & Render Functionality - 8h

### ISSUE THREAD

**Issue by memlocator** [Medo-Osman/DuplexEngine#9]
Create mesh component which will in the early prototype render.

MeshComponent holds ID for MeshResource which is in itself held in Renderer. Meshresource holds a reference/pointer to its buffer.

MeshResource should have a render functionality.

Renderer class holds MeshResources in a map.

**Comment by Blargenswarg** [comment]
Vi jobbade tillsammans på det i ca 4h. Sen fixade jag resten i 4.3h.
